import { useState, useEffect, useCallback } from 'react';
import {
  FileText,
  Download,
  Calendar,
  Clock,
  Building2,
  GraduationCap,
  AlertCircle,
  Mail,
  User,
} from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Card, CardContent } from '@/components/ui/card';
import { admitCardApi } from '@/lib/api/admit-cards';
import type { AdmitCard } from '@/lib/types';

function normalizeDate(raw: unknown): Date | null {
  if (!raw) return null;
  if (typeof raw === 'object' && raw !== null && 'epochMilliseconds' in raw) {
    const ms = (raw as { epochMilliseconds: number }).epochMilliseconds;
    const d = new Date(ms);
    return isNaN(d.getTime()) ? null : d;
  }
  if (typeof raw === 'number') {
    const d = new Date(raw);
    return isNaN(d.getTime()) ? null : d;
  }
  if (typeof raw === 'string') {
    if (/^\d{4}-\d{2}-\d{2}$/.test(raw.trim())) {
      const [y, m, day] = raw.trim().split('-').map(Number);
      return new Date(y, m - 1, day);
    }
    const d = new Date(raw);
    return isNaN(d.getTime()) ? null : d;
  }
  return null;
}

function formatDate(dateStr: string): string {
  const d = normalizeDate(dateStr);
  if (!d) return 'N/A';
  return d.toLocaleDateString('en-US', {
    weekday: 'long',
    year: 'numeric',
    month: 'long',
    day: 'numeric',
  });
}

function formatTime(time: string): string {
  const [h, m] = time.split(':');
  const hour = parseInt(h, 10);
  const ampm = hour >= 12 ? 'PM' : 'AM';
  const h12 = hour % 12 || 12;
  return `${h12}:${m} ${ampm}`;
}

export default function StudentAdmitCardPage() {
  const [cards, setCards] = useState<AdmitCard[]>([]);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState('');
  const [selectedCard, setSelectedCard] = useState<AdmitCard | null>(null);

  const fetchCards = useCallback(async () => {
    setLoading(true);
    setError('');
    try {
      const res = await admitCardApi.getMyCards();
      setCards(res.data);
      if (res.data.length > 0 && !selectedCard) {
        setSelectedCard(res.data[0]);
      }
    } catch {
      setError('Failed to load admit cards.');
    } finally {
      setLoading(false);
    }
  }, [selectedCard]);

  useEffect(() => {
    fetchCards();
  }, [fetchCards]);

  const handleDownloadPdf = (card: AdmitCard) => {
    const baseUrl = import.meta.env.VITE_API_URL || window.location.origin;
    window.open(`${baseUrl}/api/v1/admit-cards/${card.id}/pdf`, '_blank');
  };

  return (
    <div className="max-w-6xl mx-auto space-y-6">
      {/* Header */}
      <div>
        <h1 className="text-2xl font-semibold text-gray-900">My Admit Card</h1>
        <p className="text-sm text-gray-500 mt-1">
          View and download your examination admit cards
        </p>
      </div>

      {error && (
        <div className="rounded-xl border border-red-200 bg-red-50 px-4 py-3 text-sm text-red-600 flex items-center gap-2">
          <AlertCircle size={16} />
          {error}
        </div>
      )}

      {loading ? (
        <div className="py-16 text-center">
          <div className="h-5 w-5 border-2 border-primary border-t-transparent rounded-full animate-spin mx-auto mb-3" />
          <p className="text-sm text-gray-500">Loading admit cards...</p>
        </div>
      ) : cards.length === 0 ? (
        <Card>
          <CardContent className="py-16 text-center">
            <FileText size={40} className="mx-auto mb-3 text-gray-300" />
            <p className="text-sm text-gray-500">
              No admit cards available yet
            </p>
            <p className="text-xs text-gray-400 mt-1">
              Admit cards will appear here once generated by the administration
            </p>
          </CardContent>
        </Card>
      ) : (
        <div className="grid lg:grid-cols-3 gap-6">
          {/* Cards List */}
          <div className="lg:col-span-1 space-y-2">
            <h3 className="text-xs font-semibold text-gray-400 uppercase tracking-wider px-1">
              Your Exams ({cards.length})
            </h3>
            {cards.map((card) => (
              <button
                key={card.id}
                onClick={() => setSelectedCard(card)}
                className={`w-full text-left rounded-xl border p-3 transition-all cursor-pointer ${
                  selectedCard?.id === card.id
                    ? 'border-primary bg-primary-light'
                    : 'border-gray-200 bg-white hover:bg-gray-50'
                }`}
              >
                <div className="flex items-center gap-3">
                  <div
                    className={`flex items-center justify-center w-9 h-9 rounded-lg shrink-0 ${
                      selectedCard?.id === card.id
                        ? 'bg-primary/10 text-primary'
                        : 'bg-gray-100 text-gray-500'
                    }`}
                  >
                    <GraduationCap size={18} />
                  </div>
                  <div className="min-w-0">
                    <div className="text-sm font-medium text-gray-900 truncate">
                      {card.moduleName}
                    </div>
                    <div className="text-xs text-gray-500">
                      {card.examDate ? formatDate(card.examDate) : 'Date TBD'}
                    </div>
                  </div>
                </div>
              </button>
            ))}
          </div>

          {/* Admit Card Detail */}
          <div className="lg:col-span-2">
            {selectedCard ? (
              <Card className="overflow-hidden">
                {/* Card Header */}
                <div className="bg-[#1a365d] px-6 py-5 text-center">
                  <h2 className="text-lg font-bold text-white">
                    ISLINGTON COLLEGE
                  </h2>
                  <p className="text-xs text-blue-200 mt-0.5">
                    Affiliated to Staffordshire University, UK
                  </p>
                  <div className="mt-3 inline-block border border-white/30 rounded px-4 py-1">
                    <span className="text-sm font-bold text-white tracking-wider">
                      ADMIT CARD
                    </span>
                  </div>
                </div>

                <CardContent className="p-6 space-y-5">
                  {/* Student Info */}
                  <div>
                    <h3 className="text-xs font-semibold text-gray-400 uppercase tracking-wider mb-3">
                      Student Information
                    </h3>
                    <div className="grid grid-cols-2 gap-3">
                      <div className="flex items-start gap-2">
                        <User
                          size={14}
                          className="text-gray-400 mt-0.5 shrink-0"
                        />
                        <div>
                          <p className="text-xs text-gray-500">Name</p>
                          <p className="text-sm font-medium text-gray-900">
                            {selectedCard.studentName}
                          </p>
                        </div>
                      </div>
                      <div className="flex items-start gap-2">
                        <Mail
                          size={14}
                          className="text-gray-400 mt-0.5 shrink-0"
                        />
                        <div>
                          <p className="text-xs text-gray-500">Email</p>
                          <p className="text-sm font-medium text-gray-900">
                            {selectedCard.studentEmail}
                          </p>
                        </div>
                      </div>
                      <div className="flex items-start gap-2">
                        <Building2
                          size={14}
                          className="text-gray-400 mt-0.5 shrink-0"
                        />
                        <div>
                          <p className="text-xs text-gray-500">Faculty</p>
                          <p className="text-sm font-medium text-gray-900">
                            {selectedCard.facultyName}
                          </p>
                        </div>
                      </div>
                    </div>
                  </div>

                  <div className="border-t border-gray-100" />

                  {/* Exam Info */}
                  <div>
                    <h3 className="text-xs font-semibold text-gray-400 uppercase tracking-wider mb-3">
                      Examination Details
                    </h3>
                    <div className="grid grid-cols-2 gap-3">
                      <div className="flex items-start gap-2">
                        <GraduationCap
                          size={14}
                          className="text-gray-400 mt-0.5 shrink-0"
                        />
                        <div>
                          <p className="text-xs text-gray-500">Module</p>
                          <p className="text-sm font-medium text-gray-900">
                            {selectedCard.moduleName}
                            {selectedCard.moduleCode
                              ? ` (${selectedCard.moduleCode})`
                              : ''}
                          </p>
                        </div>
                      </div>
                      <div className="flex items-start gap-2">
                        <Calendar
                          size={14}
                          className="text-gray-400 mt-0.5 shrink-0"
                        />
                        <div>
                          <p className="text-xs text-gray-500">Date</p>
                          <p className="text-sm font-medium text-gray-900">
                            {selectedCard.examDate
                              ? formatDate(selectedCard.examDate)
                              : 'TBD'}
                          </p>
                        </div>
                      </div>
                      <div className="flex items-start gap-2">
                        <Clock
                          size={14}
                          className="text-gray-400 mt-0.5 shrink-0"
                        />
                        <div>
                          <p className="text-xs text-gray-500">Time</p>
                          <p className="text-sm font-medium text-gray-900">
                            {selectedCard.startTime && selectedCard.endTime
                              ? `${formatTime(selectedCard.startTime)} – ${formatTime(selectedCard.endTime)}`
                              : 'TBD'}
                            {selectedCard.duration
                              ? ` (${selectedCard.duration})`
                              : ''}
                          </p>
                        </div>
                      </div>
                    </div>
                  </div>

                  <div className="border-t border-gray-100" />

                  {/* Seating Info */}
                  <div>
                    <h3 className="text-xs font-semibold text-gray-400 uppercase tracking-wider mb-3">
                      Seating Information
                    </h3>
                    <div className="grid grid-cols-2 gap-3">
                      <div className="flex items-start gap-2">
                        <Building2
                          size={14}
                          className="text-gray-400 mt-0.5 shrink-0"
                        />
                        <div>
                          <p className="text-xs text-gray-500">Room</p>
                          <p className="text-sm font-medium text-gray-900">
                            {selectedCard.roomName ?? 'To be assigned'}
                          </p>
                        </div>
                      </div>
                      <div className="flex items-start gap-2">
                        <FileText
                          size={14}
                          className="text-gray-400 mt-0.5 shrink-0"
                        />
                        <div>
                          <p className="text-xs text-gray-500">Seat Number</p>
                          <p className="text-sm font-medium text-gray-900">
                            {selectedCard.seatNumber ?? 'To be assigned'}
                          </p>
                        </div>
                      </div>
                    </div>
                  </div>

                  <div className="border-t border-gray-100" />

                  {/* Footer */}
                  <div className="flex items-center justify-between">
                    <p className="text-[10px] text-gray-400">
                      ID: {selectedCard.id}
                    </p>
                    <Button
                      onClick={() => handleDownloadPdf(selectedCard)}
                      className="cursor-pointer"
                      size="sm"
                    >
                      <Download size={14} className="mr-2" />
                      Download PDF
                    </Button>
                  </div>
                </CardContent>
              </Card>
            ) : (
              <Card>
                <CardContent className="py-16 text-center">
                  <FileText size={40} className="mx-auto mb-3 text-gray-300" />
                  <p className="text-sm text-gray-500">
                    Select an exam to view your admit card
                  </p>
                </CardContent>
              </Card>
            )}
          </div>
        </div>
      )}
    </div>
  );
}
